// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clickable': string;
  'gridItem': string;
  'itemHeader': string;
  'itemParagraph': string;
  'itemPhoto': string;
}
export const cssExports: CssExports;
export default cssExports;
