// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'gridItem': string;
  'header': string;
  'itemHeader': string;
  'itemParagraph': string;
  'itemPhoto': string;
  'left': string;
  'popUp': string;
  'priceList': string;
  'priceRange': string;
  'prices': string;
  'right': string;
  'ticketSale': string;
  'ticketSales': string;
}
export const cssExports: CssExports;
export default cssExports;
